import Foundation
import DeviceCheck
import CryptoKit

/// Result of a successful App Attest operation.
struct AttestationResult {
    /// Base64-encoded attestation object from `DCAppAttestService.attestKey(_:clientDataHash:)`.
    let token: String
    /// The key ID generated by `DCAppAttestService.generateKey()`.
    let keyId: String
}

/// Wraps `DCAppAttestService` to produce App Attest tokens at enrollment time.
///
/// App Attest environment (development vs production) is determined by Apple based on the
/// signing identity and entitlements in the app binary — the SDK does not need to specify it.
/// The server validates the attestation against whichever Apple CA applies.
///
/// On the Simulator or devices without App Attest support, `attest(enrollmentChallenge:)`
/// returns `nil`. The caller should proceed without attestation; the server sets
/// `confidence_ceiling: "medium"` for that device.
final class AttestationProvider {

    /// Generates a fresh App Attest key and attestation token using the provided challenge.
    ///
    /// The challenge is the enrollment idempotency key, converted to Data and hashed with
    /// SHA-256 before being passed to `attestKey(_:clientDataHash:)` per Apple's requirement.
    ///
    /// - Returns: An `AttestationResult`, or `nil` if App Attest is not supported.
    func attest(enrollmentChallenge: String) async throws -> AttestationResult? {
        let service = DCAppAttestService.shared
        guard service.isSupported else {
            return nil
        }

        // Generate a fresh App Attest key for this device.
        let keyId = try await generateKey(service: service)

        // Apple requires clientDataHash = SHA256(clientData). We use the enrollment challenge
        // as clientData so the attestation is bound to this specific enrollment request.
        guard let challengeData = enrollmentChallenge.data(using: .utf8) else {
            throw AttestationError.invalidChallenge
        }
        let clientDataHash = Data(SHA256.hash(data: challengeData))

        // Attest the key — this makes a network call to Apple's servers.
        let attestationObject = try await attestKey(keyId: keyId, clientDataHash: clientDataHash, service: service)
        return AttestationResult(
            token: attestationObject.base64EncodedString(),
            keyId: keyId
        )
    }

    // MARK: - Async wrappers for iOS 15 compatibility
    // DCAppAttestService gained native async methods in iOS 16. We wrap the completion-handler
    // versions to maintain iOS 15 compatibility.

    private func generateKey(service: DCAppAttestService) async throws -> String {
        try await withCheckedThrowingContinuation { continuation in
            service.generateKey { keyId, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let keyId {
                    continuation.resume(returning: keyId)
                } else {
                    continuation.resume(throwing: AttestationError.unexpectedNilResult)
                }
            }
        }
    }

    private func attestKey(keyId: String, clientDataHash: Data, service: DCAppAttestService) async throws -> Data {
        try await withCheckedThrowingContinuation { continuation in
            service.attestKey(keyId, clientDataHash: clientDataHash) { attestation, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let attestation {
                    continuation.resume(returning: attestation)
                } else {
                    continuation.resume(throwing: AttestationError.unexpectedNilResult)
                }
            }
        }
    }
}

// MARK: - Errors

enum AttestationError: Error {
    case invalidChallenge
    case unexpectedNilResult
}
