import Foundation
import DeviceCheck
import CryptoKit

/// Result of a successful App Attest operation.
struct AttestationResult {
    /// Base64-encoded attestation object from `DCAppAttestService.attestKey(_:clientDataHash:)`.
    let token: String
    /// The key ID generated by `DCAppAttestService.generateKey()`.
    let keyId: String
}

/// Wraps `DCAppAttestService` to produce App Attest tokens at enrollment time.
///
/// App Attest environment (development vs production) is determined by Apple based on the
/// signing identity and entitlements in the app binary — the SDK does not need to specify it.
/// The server validates the attestation against whichever Apple CA applies.
///
/// On the Simulator or devices without App Attest support, `attest(enrollmentChallenge:)`
/// returns `nil`. The caller should proceed without attestation; the server sets
/// `confidence_ceiling: "medium"` for that device.
final class AttestationProvider {

    /// Whether App Attest is available on this device. False on the Simulator
    /// and hardware without App Attest support. Used to gate self-heal re-enroll
    /// so we never loop on a device that legitimately cannot attest.
    var isSupported: Bool { DCAppAttestService.shared.isSupported }

    /// Generates a fresh App Attest key and attestation token using the provided challenge.
    ///
    /// The challenge is the enrollment idempotency key, converted to Data and hashed with
    /// SHA-256 before being passed to `attestKey(_:clientDataHash:)` per Apple's requirement.
    ///
    /// - Returns: An `AttestationResult`, or `nil` if App Attest is not supported.
    func attest(enrollmentChallenge: String) async throws -> AttestationResult? {
        let service = DCAppAttestService.shared
        guard service.isSupported else {
            return nil
        }

        // Generate a fresh App Attest key for this device.
        let keyId = try await generateKey(service: service)

        // Apple requires clientDataHash = SHA256(clientData). We use the enrollment challenge
        // as clientData so the attestation is bound to this specific enrollment request.
        guard let challengeData = enrollmentChallenge.data(using: .utf8) else {
            throw AttestationError.invalidChallenge
        }
        let clientDataHash = Data(SHA256.hash(data: challengeData))

        // Attest the key — this makes a network call to Apple's servers.
        let attestationObject = try await attestKey(keyId: keyId, clientDataHash: clientDataHash, service: service)
        return AttestationResult(
            token: attestationObject.base64EncodedString(),
            keyId: keyId
        )
    }

    // MARK: - Async wrappers for iOS 15 compatibility
    // DCAppAttestService gained native async methods in iOS 16. We wrap the completion-handler
    // versions to maintain iOS 15 compatibility.

    private func generateKey(service: DCAppAttestService) async throws -> String {
        try await withCheckedThrowingContinuation { continuation in
            service.generateKey { keyId, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let keyId {
                    continuation.resume(returning: keyId)
                } else {
                    continuation.resume(throwing: AttestationError.unexpectedNilResult)
                }
            }
        }
    }

    private func attestKey(keyId: String, clientDataHash: Data, service: DCAppAttestService) async throws -> Data {
        try await withCheckedThrowingContinuation { continuation in
            service.attestKey(keyId, clientDataHash: clientDataHash) { attestation, error in
                if let error {
                    continuation.resume(throwing: error)
                } else if let attestation {
                    continuation.resume(returning: attestation)
                } else {
                    continuation.resume(throwing: AttestationError.unexpectedNilResult)
                }
            }
        }
    }

    // MARK: - Sign-time re-attestation

    /// Produces a fresh App Attest assertion over the given `clientDataHash`,
    /// using the App Attest key generated at enrollment.
    ///
    /// Called from `SignPayloadManager` on the high-confidence path. The
    /// assertion proves the app bundle and device integrity are still in a
    /// trustworthy state at sign time — narrowing the window between
    /// enrollment-time attestation and sign-time use.
    ///
    /// - Parameters:
    ///   - keyId: The App Attest key ID persisted at enrollment.
    ///   - clientDataHash: SHA-256 hash of `canonical_payload || challenge`
    ///     (the same bytes the SE key signed). Apple's API signs over
    ///     `authenticatorData || clientDataHash`; the server later verifies
    ///     that clientDataHash matches the same signingInputHash.
    /// - Returns: Base64-encoded CBOR assertion ready to ship to
    ///   `POST /v1/sign/:id/complete` as `app_attest_assertion`. `nil` when
    ///   App Attest is unsupported on this device (Simulator, older iOS).
    func generateAssertion(keyId: String, clientDataHash: Data) async throws -> String? {
        let service = DCAppAttestService.shared
        guard service.isSupported else {
            return nil
        }
        let assertion: Data = try await withCheckedThrowingContinuation { cont in
            service.generateAssertion(keyId, clientDataHash: clientDataHash) { result, error in
                if let error {
                    cont.resume(throwing: error)
                } else if let result {
                    cont.resume(returning: result)
                } else {
                    cont.resume(throwing: AttestationError.unexpectedNilResult)
                }
            }
        }
        return assertion.base64EncodedString()
    }
}

// MARK: - Errors

enum AttestationError: Error {
    case invalidChallenge
    case unexpectedNilResult
}
